name: Deploy IoT Edge Modules

on:
  workflow_dispatch:
    inputs:
      device_id:
        description: 'Device ID'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Input
        run: |
          echo "DEVICE_ID: ${{ inputs.device_id }}"
