name: Deploy IoT Edge Modules

on:
  workflow_dispatch:
    inputs:
      device_id:
        description: 'Device ID'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Input
        run: |
          echo "DEVICE_ID: ${{ inputs.device_id }}"

      - name: Login to Azure Container Registry
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
