name: Build and Push to ACR
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: recursive
            token: ${{ secrets.GH_PAT }}
            persist-credentials: true

      - name: Log in to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.AZURE_URL }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Alto OS to ACR 
        run: |
            cd alto_os
            docker build -t ${{ secrets.AZURE_URL }}/alto_os:${{ github.ref_name }} .
            docker push ${{ secrets.AZURE_URL }}/alto_os:${{ github.ref_name }}

      - name: Build and Push Alto Dash to ACR
        run: |
            cd alto-dash
            docker build -t ${{ secrets.AZURE_URL }}/alto-dash:${{ github.ref_name }} .
            docker push ${{ secrets.AZURE_URL }}/alto-dash:${{ github.ref_name }}

      - name: Build and Push Alto CERO Interface to ACR
        run: |
            cd alto-cero-interface
            docker build -t ${{ secrets.AZURE_URL }}/alto-cero-interface:${{ github.ref_name }} .
            docker push ${{ secrets.AZURE_URL }}/alto-cero-interface:${{ github.ref_name }}

      - name: Build and Push Alto CERO Automation Backend to ACR
        run: |
            cd alto-cero-automation-backend
            docker build -t ${{ secrets.AZURE_URL }}/alto-cero-automation-backend:${{ github.ref_name }} .
            docker push ${{ secrets.AZURE_URL }}/alto-cero-automation-backend:${{ github.ref_name }}

            
            
            
            
            
            

    #   - name: Build and Push Alto OS to ACR 
    #     uses: docker/build-push-action@v2
    #     with:
    #         push: true
    #         tags: ${{ secrets.AZURE_URL }}/alto_os:${{ github.ref_name }}
    #         file: alto_os/Dockerfile

    #   - name: Build and Push Alto Dash to ACR
    #     uses: docker/build-push-action@v2
    #     with:
    #         push: true
    #         tags: ${{ secrets.AZURE_URL }}/alto-dash:${{ github.ref_name }}
    #         file: alto-dash/Dockerfile

    #   - name: Build and Push Alto CERO Interface to ACR
    #     uses: docker/build-push-action@v2
    #     with:
    #         push: true
    #         tags: ${{ secrets.AZURE_URL }}/alto-cero-interface:${{ github.ref_name }}
    #         file: alto-cero-interface/Dockerfile

    #   - name: Build and Push Alto CERO Automation Backend to ACR
    #     uses: docker/build-push-action@v2
    #     with:
    #         push: true
    #         tags: ${{ secrets.AZURE_URL }}/alto-cero-automation-backend:${{ github.ref_name }}
    #         file: alto-cero-automation-backend/Dockerfile
