name: Build and Push to ACR
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: recursive
            token: ${{ secrets.GH_PAT }}
            persist-credentials: true

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
            login-server: ${{ secrets.AZURE_URL }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Alto OS to ACR 
        uses: docker/build-push-action@v2
        with:
            push: true
            tags: ${{ secrets.AZURE_URL }}/alto_os:${{ github.ref_name }}
            file: alto_os/Dockerfile

      - name: Build and Push Alto Dash to ACR
        uses: docker/build-push-action@v2
        with:
            push: true
            tags: ${{ secrets.AZURE_URL }}/alto-dash:${{ github.ref_name }}
            file: alto-dash/Dockerfile

      - name: Build and Push Alto CERO Interface to ACR
        uses: docker/build-push-action@v2
        with:
            push: true
            tags: ${{ secrets.AZURE_URL }}/alto-cero-interface:${{ github.ref_name }}
            file: alto-cero-interface/Dockerfile

      - name: Build and Push Alto CERO Automation Backend to ACR
        uses: docker/build-push-action@v2
        with:
            push: true
            tags: ${{ secrets.AZURE_URL }}/alto-cero-automation-backend:${{ github.ref_name }}
            file: alto-cero-automation-backend/Dockerfile
